In [2]:
import numpy as np

In [129]:
#seed fuction is for random function jo bhi isse use krenga uska same number aayega also same number has same randm numbers
np.random.seed(50)

In [7]:
arr = np.random.randint(1,20,(3,3))

In [8]:
arr

array([[14,  6,  3],
       [ 8, 16,  5],
       [15,  4,  7]], dtype=int32)

### Indexing

In [12]:
#0,1,2....pehle row fir coloumn
arr[2]

array([15,  4,  7], dtype=int32)

In [11]:
#row
arr[2][0]

np.int32(15)

In [13]:
#also if i want i can write in one bracket
arr[2,0]

np.int32(15)

In [14]:
arr = np.random.randint(1,20,(3,5,4))

In [15]:
arr

array([[[12, 18, 11, 10],
        [ 1,  7,  3, 16],
        [10,  4,  3, 13],
        [ 1,  4,  3, 11],
        [17, 15,  1,  1]],

       [[12,  8, 15, 14],
        [ 8,  5,  5,  1],
        [12,  1, 14, 14],
        [ 2, 10, 12,  6],
        [ 1, 16,  6,  7]],

       [[ 2,  5,  5, 13],
        [15,  5, 12,  1],
        [ 6,  9, 13, 12],
        [ 4,  7, 19,  9],
        [16,  6, 16,  5]]], dtype=int32)

In [16]:
arr[1]

array([[12,  8, 15, 14],
       [ 8,  5,  5,  1],
       [12,  1, 14, 14],
       [ 2, 10, 12,  6],
       [ 1, 16,  6,  7]], dtype=int32)

In [18]:
arr[2]

array([[ 2,  5,  5, 13],
       [15,  5, 12,  1],
       [ 6,  9, 13, 12],
       [ 4,  7, 19,  9],
       [16,  6, 16,  5]], dtype=int32)

In [19]:
arr[1,3]

array([ 2, 10, 12,  6], dtype=int32)

In [20]:
arr[1,3,2]

np.int32(12)

#### Slicing

In [21]:
arr= np.random.randint(1,20,(5,5))

In [22]:
arr

array([[ 5, 19, 16, 11, 18],
       [ 9, 15, 12,  8, 10],
       [ 2,  9,  4,  4, 11],
       [ 4,  7, 16,  1, 19],
       [12,  2, 18, 15, 15]], dtype=int32)

In [130]:
#pehle row ki fir coloumn ki(start :upto but not included)
arr[2:4 , 1:3]

array([[7, 8]])

In [26]:
arr[2]

array([ 2,  9,  4,  4, 11], dtype=int32)

In [27]:
arr = np.random.randint(1,20,(3,5,4))

In [28]:
arr

array([[[ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12],
        [ 2,  6, 14,  4],
        [15,  3,  9,  7]],

       [[ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16],
        [ 4,  5, 10,  5],
        [ 8, 18, 14, 10]],

       [[15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1],
        [ 9, 16, 14,  1],
        [11, 15, 13,  5]]], dtype=int32)

In [29]:
arr[2]

array([[15, 14, 16,  4],
       [ 7, 13, 11, 15],
       [ 1, 14, 14,  1],
       [ 9, 16, 14,  1],
       [11, 15, 13,  5]], dtype=int32)

In [36]:
#layer2,row 2: , col1:upto col3
arr[2,2:,0:3]

array([[ 1, 14, 14],
       [ 9, 16, 14],
       [11, 15, 13]], dtype=int32)

In [37]:
arr[2,2:,0:3][1:,0:2]

array([[ 9, 16],
       [11, 15]], dtype=int32)

In [38]:
arr

array([[[ 6,  7, 10,  5],
        [10,  1, 16, 17],
        [18, 17,  5, 12],
        [ 2,  6, 14,  4],
        [15,  3,  9,  7]],

       [[ 1, 15, 14,  5],
        [17, 15,  5, 12],
        [17, 18, 15, 16],
        [ 4,  5, 10,  5],
        [ 8, 18, 14, 10]],

       [[15, 14, 16,  4],
        [ 7, 13, 11, 15],
        [ 1, 14, 14,  1],
        [ 9, 16, 14,  1],
        [11, 15, 13,  5]]], dtype=int32)

In [43]:
arr[:,1:4]

array([[[10,  1, 16, 17],
        [18, 17,  5, 12],
        [ 2,  6, 14,  4]],

       [[17, 15,  5, 12],
        [17, 18, 15, 16],
        [ 4,  5, 10,  5]],

       [[ 7, 13, 11, 15],
        [ 1, 14, 14,  1],
        [ 9, 16, 14,  1]]], dtype=int32)

In [60]:
arr[2 , -1 ,-2]

np.int32(13)

In [61]:
arr[:,1:4,1:3]

array([[[ 1, 16],
        [17,  5],
        [ 6, 14]],

       [[15,  5],
        [18, 15],
        [ 5, 10]],

       [[13, 11],
        [14, 14],
        [16, 14]]], dtype=int32)

In [62]:
arr1 = np.random.randint(1,50,(5,5,5))

In [63]:
arr1

array([[[14, 25, 47, 48, 35],
        [28, 46, 40,  6, 10],
        [21,  8,  9, 18, 16],
        [44,  5, 45, 19, 11],
        [ 6, 33, 24, 26, 46]],

       [[26, 20, 17,  2, 41],
        [36,  4, 11, 33, 19],
        [10, 48, 11, 42,  7],
        [47, 22, 22,  2, 29],
        [ 7, 48, 31, 26, 29]],

       [[ 1, 26, 28, 33, 36],
        [34, 28, 48, 44,  3],
        [36, 24,  6,  9, 37],
        [ 3,  2,  8, 37, 36],
        [32, 18, 38, 36, 21]],

       [[44, 10, 43, 31, 18],
        [14, 13, 36, 18,  1],
        [12, 13, 29,  1,  7],
        [45, 29, 24,  2, 37],
        [13, 21, 33, 37, 28]],

       [[40, 46,  4, 46, 26],
        [16, 31,  5, 30, 18],
        [12, 39, 36, 32, 30],
        [36, 42, 15, 14, 28],
        [ 9, 40, 32, 47,  9]]], dtype=int32)

In [131]:
arr1[:,4]

array([[ 6, 33, 24, 26, 46],
       [ 7, 48, 31, 26, 29],
       [32, 18, 38, 36, 21],
       [13, 21, 33, 37, 28],
       [ 9, 40, 32, 47,  9]], dtype=int32)

In [65]:
arr[:,2:4 , 1:3]

array([[[17,  5],
        [ 6, 14]],

       [[18, 15],
        [ 5, 10]],

       [[14, 14],
        [16, 14]]], dtype=int32)

In [67]:
arr= np.random.randint(1,10,(4,4))

In [68]:
arr

array([[1, 7, 8, 9],
       [4, 4, 9, 4],
       [1, 1, 7, 7],
       [4, 7, 4, 9]], dtype=int32)

In [70]:
#-1 se last row bahr aa jati hai
arr[-1]

array([4, 7, 4, 9], dtype=int32)

In [71]:
arr[-1,1]

np.int32(7)

In [76]:
#u can change the number by positioning 
arr[-1,1] = 9

In [77]:
arr

array([[1, 7, 8, 9],
       [4, 4, 9, 4],
       [1, 1, 7, 7],
       [4, 9, 4, 9]], dtype=int32)

In [82]:
#agr sabhi values ki baat change krni ho
arr[2:,0:2] = 5

In [83]:
arr

array([[1, 7, 8, 9],
       [4, 4, 9, 4],
       [5, 5, 7, 7],
       [5, 5, 4, 9]], dtype=int32)

In [128]:
a=arr[-2:,-2:]

In [122]:
a

array([[4, 5],
       [7, 8]])

In [123]:
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [124]:
a[0,-1] = 100

In [125]:
#a mai bhi change ho geya 
a

array([[  4, 100],
       [  7,   8]])

In [132]:
#or  original array me bhi change hogeya 
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [133]:
a[0,-1] = 100

In [134]:
a

array([[  4, 100],
       [  7,   8]])

In [135]:
a

array([[  4, 100],
       [  7,   8]])

In [136]:
arr

array([[ 50,   1,   2],
       [  3,   4, 100],
       [  6,   7,   8]])

In [110]:
arr = np.arange(9)
arr = arr.reshape(3,3)

In [111]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
a = arr

In [138]:
b = arr.copy()

In [139]:
a[0][0] = 50

In [140]:
arr

array([[ 50,   1,   2],
       [  3,   4, 100],
       [  6,   7,   8]])

In [141]:
b[0,0] = 100

In [142]:
b

array([[100,   1,   2],
       [  3,   4, 100],
       [  6,   7,   8]])

In [143]:
arr

array([[ 50,   1,   2],
       [  3,   4, 100],
       [  6,   7,   8]])