In [1]:
import numpy as np

In [2]:
#seed fuction is for random function jo bhi isse use krenga uska same number aayega also same number has same randm numbers
np.random.seed(50)

In [3]:
arr = np.random.randint(1,20,(3,3))

In [4]:
arr

array([[17,  1, 12],
       [14,  2,  5],
       [ 7,  6,  7]], dtype=int32)

### Indexing

In [5]:
#0,1,2....pehle row fir coloumn
arr[2]

array([7, 6, 7], dtype=int32)

In [6]:
#row
arr[2][0]

np.int32(7)

In [7]:
#coloumn
arr[:,2]

array([12,  5,  7], dtype=int32)

In [8]:
#also if i want i can write in one bracket...the row 2 element 0
arr[2,0]

np.int32(7)

In [9]:
arr = np.random.randint(1,20,(3,5,4))

In [15]:
arr

array([[[12, 18, 11, 10],
        [ 1,  7,  3, 16],
        [10,  4,  3, 13],
        [ 1,  4,  3, 11],
        [17, 15,  1,  1]],

       [[12,  8, 15, 14],
        [ 8,  5,  5,  1],
        [12,  1, 14, 14],
        [ 2, 10, 12,  6],
        [ 1, 16,  6,  7]],

       [[ 2,  5,  5, 13],
        [15,  5, 12,  1],
        [ 6,  9, 13, 12],
        [ 4,  7, 19,  9],
        [16,  6, 16,  5]]], dtype=int32)

In [10]:
arr[1]

array([[13,  1,  4,  3],
       [11, 17, 15,  1],
       [ 1, 12,  8, 15],
       [14,  8,  5,  5],
       [ 1, 12,  1, 14]], dtype=int32)

In [11]:
arr[2]

array([[14,  2, 10, 12],
       [ 6,  1, 16,  6],
       [ 7,  2,  5,  5],
       [13, 15,  5, 12],
       [ 1,  6,  9, 13]], dtype=int32)

In [12]:
arr[1,3]

array([14,  8,  5,  5], dtype=int32)

In [13]:
arr[1,3,2]

np.int32(5)

In [16]:
arr[0]

array([[14,  6,  3,  8],
       [16,  5, 15,  4],
       [ 7, 12, 18, 11],
       [10,  1,  7,  3],
       [16, 10,  4,  3]], dtype=int32)

In [17]:
arr[0,2]

array([ 7, 12, 18, 11], dtype=int32)

In [18]:
arr[-1]

array([[14,  2, 10, 12],
       [ 6,  1, 16,  6],
       [ 7,  2,  5,  5],
       [13, 15,  5, 12],
       [ 1,  6,  9, 13]], dtype=int32)

In [19]:
arr[::-1]

array([[[14,  2, 10, 12],
        [ 6,  1, 16,  6],
        [ 7,  2,  5,  5],
        [13, 15,  5, 12],
        [ 1,  6,  9, 13]],

       [[13,  1,  4,  3],
        [11, 17, 15,  1],
        [ 1, 12,  8, 15],
        [14,  8,  5,  5],
        [ 1, 12,  1, 14]],

       [[14,  6,  3,  8],
        [16,  5, 15,  4],
        [ 7, 12, 18, 11],
        [10,  1,  7,  3],
        [16, 10,  4,  3]]], dtype=int32)

In [20]:
arr[0:3]

array([[[14,  6,  3,  8],
        [16,  5, 15,  4],
        [ 7, 12, 18, 11],
        [10,  1,  7,  3],
        [16, 10,  4,  3]],

       [[13,  1,  4,  3],
        [11, 17, 15,  1],
        [ 1, 12,  8, 15],
        [14,  8,  5,  5],
        [ 1, 12,  1, 14]],

       [[14,  2, 10, 12],
        [ 6,  1, 16,  6],
        [ 7,  2,  5,  5],
        [13, 15,  5, 12],
        [ 1,  6,  9, 13]]], dtype=int32)

In [21]:
arr

array([[[14,  6,  3,  8],
        [16,  5, 15,  4],
        [ 7, 12, 18, 11],
        [10,  1,  7,  3],
        [16, 10,  4,  3]],

       [[13,  1,  4,  3],
        [11, 17, 15,  1],
        [ 1, 12,  8, 15],
        [14,  8,  5,  5],
        [ 1, 12,  1, 14]],

       [[14,  2, 10, 12],
        [ 6,  1, 16,  6],
        [ 7,  2,  5,  5],
        [13, 15,  5, 12],
        [ 1,  6,  9, 13]]], dtype=int32)

#### Slicing

In [22]:
arr= np.random.randint(1,20,(5,5))

In [23]:
arr

array([[12,  4,  7, 19,  9],
       [16,  6, 16,  5,  5],
       [19, 16, 11, 18,  9],
       [15, 12,  8, 10,  2],
       [ 9,  4,  4, 11,  4]], dtype=int32)

In [26]:
#pehle row ki fir coloumn ki(start :upto but not included)
arr[2:5 , 1:3]

array([[16, 11],
       [12,  8],
       [ 4,  4]], dtype=int32)

In [27]:
arr[2]

array([19, 16, 11, 18,  9], dtype=int32)

In [28]:
arr = np.random.randint(1,20,(3,5,4))

In [30]:
arr

array([[[ 7, 16,  1, 19],
        [12,  2, 18, 15],
        [15,  6,  7, 10],
        [ 5, 10,  1, 16],
        [17, 18, 17,  5]],

       [[12,  2,  6, 14],
        [ 4, 15,  3,  9],
        [ 7,  1, 15, 14],
        [ 5, 17, 15,  5],
        [12, 17, 18, 15]],

       [[16,  4,  5, 10],
        [ 5,  8, 18, 14],
        [10, 15, 14, 16],
        [ 4,  7, 13, 11],
        [15,  1, 14, 14]]], dtype=int32)

In [31]:
arr[2]

array([[16,  4,  5, 10],
       [ 5,  8, 18, 14],
       [10, 15, 14, 16],
       [ 4,  7, 13, 11],
       [15,  1, 14, 14]], dtype=int32)

In [38]:
#layer2,row 2: , col1:upto col3
arr[2,2:,0:3]

array([[10, 15, 14],
       [ 4,  7, 13],
       [15,  1, 14]], dtype=int32)

In [39]:
arr[2,2:,0:3][1:,0:2]

array([[ 4,  7],
       [15,  1]], dtype=int32)

In [40]:
arr

array([[[ 7, 16,  1, 19],
        [12,  2, 18, 15],
        [15,  6,  7, 10],
        [ 5, 10,  1, 16],
        [17, 18, 17,  5]],

       [[12,  2,  6, 14],
        [ 4, 15,  3,  9],
        [ 7,  1, 15, 14],
        [ 5, 17, 15,  5],
        [12, 17, 18, 15]],

       [[16,  4,  5, 10],
        [ 5,  8, 18, 14],
        [10, 15, 14, 16],
        [ 4,  7, 13, 11],
        [15,  1, 14, 14]]], dtype=int32)

In [41]:
arr[:,1:4]

array([[[12,  2, 18, 15],
        [15,  6,  7, 10],
        [ 5, 10,  1, 16]],

       [[ 4, 15,  3,  9],
        [ 7,  1, 15, 14],
        [ 5, 17, 15,  5]],

       [[ 5,  8, 18, 14],
        [10, 15, 14, 16],
        [ 4,  7, 13, 11]]], dtype=int32)

In [44]:
arr[2 ,-1]

array([15,  1, 14, 14], dtype=int32)

In [45]:
#2 row,last row,last second col
arr[2,-1,-2]

np.int32(14)

In [46]:
#for all
arr[:,]

array([[[ 7, 16,  1, 19],
        [12,  2, 18, 15],
        [15,  6,  7, 10],
        [ 5, 10,  1, 16],
        [17, 18, 17,  5]],

       [[12,  2,  6, 14],
        [ 4, 15,  3,  9],
        [ 7,  1, 15, 14],
        [ 5, 17, 15,  5],
        [12, 17, 18, 15]],

       [[16,  4,  5, 10],
        [ 5,  8, 18, 14],
        [10, 15, 14, 16],
        [ 4,  7, 13, 11],
        [15,  1, 14, 14]]], dtype=int32)

In [51]:
#sabh ki first row
arr[:,1]

array([[12,  2, 18, 15],
       [ 4, 15,  3,  9],
       [ 5,  8, 18, 14]], dtype=int32)

In [54]:
#sabhi k 2 rows between 1,3
arr[:,1:3]

array([[[12,  2, 18, 15],
        [15,  6,  7, 10]],

       [[ 4, 15,  3,  9],
        [ 7,  1, 15, 14]],

       [[ 5,  8, 18, 14],
        [10, 15, 14, 16]]], dtype=int32)

In [56]:
arr[:,1:3 ,1:3]

array([[[ 2, 18],
        [ 6,  7]],

       [[15,  3],
        [ 1, 15]],

       [[ 8, 18],
        [15, 14]]], dtype=int32)

In [57]:
arr[:,1:3 ,1:3][1]

array([[15,  3],
       [ 1, 15]], dtype=int32)

In [62]:
arr[1,1:3,1:3]

array([[15,  3],
       [ 1, 15]], dtype=int32)

In [63]:
arr1 = np.random.randint(1,50,(5,5,5))

In [64]:
arr1

array([[[ 1,  9, 48, 46, 33],
        [43, 15, 45,  5, 41],
        [43, 43, 33,  8, 37],
        [26, 12, 27, 46, 33],
        [41, 24, 48, 39,  4]],

       [[29,  6, 44, 29,  2],
        [48, 36,  4,  1, 47],
        [43, 13, 38, 13, 33],
        [22, 44, 15, 20, 46],
        [17, 34, 20, 48, 44]],

       [[33,  5, 46, 42, 16],
        [19, 32, 23,  3,  6],
        [ 2, 34, 26, 11, 19],
        [ 9, 15, 18, 16, 29],
        [34, 24, 42, 40, 23]],

       [[42, 21, 29, 20, 20],
        [47, 37,  6,  1, 40],
        [40, 49, 28, 25,  3],
        [11, 10,  7, 42, 38],
        [46, 19, 45, 38, 11]],

       [[38, 16, 14, 22,  8],
        [39,  1, 44, 49, 40],
        [11, 15,  8, 27, 36],
        [26, 11, 46, 16,  1],
        [30, 46,  1, 43, 20]]], dtype=int32)

In [71]:
arr1[:,1:4 , 1:5][1]

array([[36,  4,  1, 47],
       [13, 38, 13, 33],
       [44, 15, 20, 46]], dtype=int32)

In [72]:
arr[:,2:4 , 1:3]

array([[[ 6,  7],
        [10,  1]],

       [[ 1, 15],
        [17, 15]],

       [[15, 14],
        [ 7, 13]]], dtype=int32)

In [73]:
arr= np.random.randint(1,10,(4,4))

In [74]:
arr

array([[1, 5, 2, 5],
       [5, 6, 9, 3],
       [3, 3, 2, 8],
       [6, 6, 5, 8]], dtype=int32)

In [75]:
#-1 se last row bahr aa jati hai
arr[-1]

array([6, 6, 5, 8], dtype=int32)

In [76]:
arr[-1,1]

np.int32(6)

In [77]:
#u can change the number by positioning 
arr[-1,1] = 9

In [78]:
arr

array([[1, 5, 2, 5],
       [5, 6, 9, 3],
       [3, 3, 2, 8],
       [6, 9, 5, 8]], dtype=int32)

In [89]:
arr[2:,0:2]

array([[5, 5],
       [5, 5]], dtype=int32)

In [90]:
arr

array([[1, 5, 2, 5],
       [5, 6, 9, 3],
       [5, 5, 2, 8],
       [5, 5, 5, 8]], dtype=int32)

In [91]:
#agr sabhi values ki baat change krni ho
arr[2:,0:2] = 5

In [92]:
arr

array([[1, 5, 2, 5],
       [5, 6, 9, 3],
       [5, 5, 2, 8],
       [5, 5, 5, 8]], dtype=int32)

In [93]:
#agr hum usse kisi varriable me save kr lee
a=arr[-2:,-2:]

In [94]:
a

array([[2, 8],
       [5, 8]], dtype=int32)

In [95]:
arr

array([[1, 5, 2, 5],
       [5, 6, 9, 3],
       [5, 5, 2, 8],
       [5, 5, 5, 8]], dtype=int32)

In [96]:
a[0,-1] = 100

In [97]:
#a mai bhi change ho geya 
a

array([[  2, 100],
       [  5,   8]], dtype=int32)

In [99]:
#or  original array me bhi change hogeya isiloye numpy baki orthers se fast hota hai
arr

array([[  1,   5,   2,   5],
       [  5,   6,   9,   3],
       [  5,   5,   2, 100],
       [  5,   5,   5,   8]], dtype=int32)

In [100]:
a[0,-1] = 100

In [101]:
a

array([[  2, 100],
       [  5,   8]], dtype=int32)

In [102]:
a

array([[  2, 100],
       [  5,   8]], dtype=int32)

In [103]:
arr

array([[  1,   5,   2,   5],
       [  5,   6,   9,   3],
       [  5,   5,   2, 100],
       [  5,   5,   5,   8]], dtype=int32)

In [104]:
a=arr[-2:,-2:]

In [105]:
a

array([[  2, 100],
       [  5,   8]], dtype=int32)

In [107]:
#agr simple aise krte hai too original me bhi change hota hai but agr hum.copy ka use 
#krte hai too hamare pass bss copy banegi original me change nhi hogga

In [111]:
a=arr[-2:,2:].copy()

In [115]:
a[0,1]=56

In [118]:
#copy me change hogga
a

array([[ 2, 56],
       [ 5,  8]], dtype=int32)

In [119]:
#but original me change nhi hogga
arr

array([[  1,   5,   2,   5],
       [  5,   6,   9,   3],
       [  5,   5,   2, 100],
       [  5,   5,   5,   8]], dtype=int32)

In [120]:
arr = np.arange(9)
arr = arr.reshape(3,3)

In [121]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
#isme agr change krenge too original me bhi hogga
a = arr

In [128]:
#or agr isme agr change krenge too srf copy b me change hoga original me change nhi hoga
b = arr.copy()

In [129]:
a[0][0] = 50

In [130]:
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [131]:
b[0,0] = 100

In [132]:
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [133]:
arr

array([[50,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])