In [1]:
import numpy as np

## Broadcasting

In [6]:
arr =np.arange(0,9)
arr = arr.reshape(3,3)

In [7]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [10]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
a = np.array([1,2])
b = np.array([3,4])

In [12]:
a

array([1, 2])

In [13]:
b

array([3, 4])

In [14]:
a+b

array([4, 6])

In [15]:
a-b

array([-2, -2])

In [16]:
a*b

array([3, 8])

In [17]:
a/b

array([0.33333333, 0.5       ])

In [18]:
a//b

array([0, 0])